version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.landawn:streamex
    versions:
    - "> 1.0.1"
  - dependency-name: net.sf.trove4j:trove4j
    versions:
    - "> 2.1.0"
  - dependency-name: org.apache.maven:maven-artifact
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven:maven-artifact
    versions:
    - ">= 3.8.a, < 3.9"
  - dependency-name: org.apache.maven:maven-compat
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven:maven-compat
    versions:
    - ">= 3.8.a, < 3.9"
  - dependency-name: org.apache.maven:maven-core
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven:maven-core
    versions:
    - ">= 3.8.a, < 3.9"
  - dependency-name: org.apache.maven:maven-model
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven:maven-model
    versions:
    - ">= 3.8.a, < 3.9"
  - dependency-name: org.apache.maven:maven-plugin-api
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven:maven-plugin-api
    versions:
    - ">= 3.8.a, < 3.9"
  - dependency-name: org.apache.maven:maven-repository-metadata
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven:maven-repository-metadata
    versions:
    - ">= 3.8.a, < 3.9"
  - dependency-name: org.apache.maven:maven-settings
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven:maven-settings
    versions:
    - ">= 3.8.a, < 3.9"
  - dependency-name: org.apache.maven.plugin-tools:maven-plugin-annotations
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven.plugin-tools:maven-plugin-tools-annotations
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.apache.maven.plugin-tools:maven-plugin-tools-api
    versions:
    - "< 3.7, >= 3.6.a"
  - dependency-name: org.jdom:jdom
    versions:
    - "> 1.1.3"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "> 0.22.5"
  - dependency-name: org.picocontainer:picocontainer
    versions:
    - "> 1.3"
  - dependency-name: com.github.gantsign.parent:kotlin-parent
    versions:
    - 2.9.0
