name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    uses: gantsign/workflows/.github/workflows/maven-build.yml@v1
    with:
      java-version: '11'

  deploy:
    name: Deploy
    needs: build
    if: github.repository == 'gantsign/kotlin-maven-plugin-tools'
    uses: gantsign/workflows/.github/workflows/maven-deploy.yml@v1
    with:
      java-version: '11'
    secrets: inherit
